namespace Tests.FrameworkTests
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using NUnit.Framework;
    using NUnit.Framework.Legacy;
    using Tiver.Fowl.Core.Enums;
    using Tiver.Fowl.Core.Reporting;

    /// <summary>
    /// Unit tests for HtmlReportGenerator - these render the report template from synthetic
    /// data and don't require a browser or a real test run.
    /// </summary>
    [TestFixture]
    public class HtmlReportGeneratorTests
    {
        /// <summary>A valid 1x1 transparent PNG, used to verify screenshot embedding.</summary>
        private const string OnePixelPng =
            "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

        [Test]
        public void Generate_EmbedsScreenshotForFailedTest()
        {
            // Full pipeline: a Screenshot log entry must end up as an inline data URI in the report.
            // Triple '$' so the JSON's trailing '}}' stays literal - only '{{{...}}}' interpolates.
            var results = ParseLog($$$"""
{"Timestamp":"2025-12-18T10:00:00.0000000+00:00","Level":"Information","MessageTemplate":"Step #{Step} :: {Text}","Properties":{"Step":1,"Text":"Step before failure","LogType":"TestStep","TestName":"Tests.Sample.FailingTest","SessionId":"20251218-100000-000-1234"}}
{"Timestamp":"2025-12-18T10:00:01.0000000+00:00","Level":"Information","MessageTemplate":"{Name} :: {Action}","Properties":{"Name":"Browser","Action":"Screenshot taken","LogType":"Screenshot","Base64":"{{{OnePixelPng}}}","TestName":"Tests.Sample.FailingTest","SessionId":"20251218-100000-000-1234"}}
{"Timestamp":"2025-12-18T10:00:02.0000000+00:00","Level":"Information","MessageTemplate":"Test result - '{TestResult}'","Properties":{"TestResult":"Failed","LogType":"TestResult","TestName":"Tests.Sample.FailingTest","SessionId":"20251218-100000-000-1234"}}
""");

            ClassicAssert.AreEqual(1, results.Count);
            ClassicAssert.AreEqual(TestResult.Failed, results[0].Result);
            ClassicAssert.AreEqual(OnePixelPng, results[0].ScreenshotBase64);

            var html = GenerateHtml(results);

            StringAssert.Contains($"src=\"data:image/png;base64,{OnePixelPng}\"", html);
        }

        [Test]
        public void Generate_OmitsScreenshotForPassedTest()
        {
            // Screenshots are only rendered for failures - a passing test must not carry one
            var record = CreateRecord("Tests.Sample.PassingTest", TestResult.Passed);
            record.ScreenshotBase64 = OnePixelPng;

            var html = GenerateHtml([record]);

            StringAssert.DoesNotContain("data:image/png;base64,", html);
        }

        [Test]
        public void Generate_RendersErrorMessageAndStackTraceForFailedTest()
        {
            var results = ParseLog("""
{"Timestamp":"2025-12-18T10:00:00.0000000+00:00","Level":"Error","MessageTemplate":"Intentional failure for report testing","Exception":"NUnit.Framework.AssertionException: Expected 42\n   at Tests.Sample.FailingTest()","Properties":{"TestName":"Tests.Sample.FailingTest","SessionId":"20251218-100000-000-1234"}}
{"Timestamp":"2025-12-18T10:00:01.0000000+00:00","Level":"Information","MessageTemplate":"Test result - '{TestResult}'","Properties":{"TestResult":"Failed","LogType":"TestResult","TestName":"Tests.Sample.FailingTest","SessionId":"20251218-100000-000-1234"}}
""");

            ClassicAssert.AreEqual(1, results.Count);

            var html = GenerateHtml(results);

            StringAssert.Contains("Intentional failure for report testing", html);
            StringAssert.Contains("at Tests.Sample.FailingTest()", html);

            // Failed tests are expanded by default so the failure is visible without interaction.
            // Anchored on class="..." because the template's own CSS/JS also mention these names.
            StringAssert.Contains("class=\"test-row test-expanded", html);
            StringAssert.DoesNotContain("class=\"test-details hidden", html);
        }

        [Test]
        public void Generate_HidesDetailsForPassedTest()
        {
            var html = GenerateHtml([CreateRecord("Tests.Sample.PassingTest", TestResult.Passed)]);

            StringAssert.Contains("class=\"test-details hidden", html);
            StringAssert.DoesNotContain("class=\"test-row test-expanded", html);
        }

        [Test]
        public void Generate_ReplacesAllTemplatePlaceholders()
        {
            var html = GenerateHtml([CreateRecord("Tests.Sample.PassingTest", TestResult.Passed)]);

            // Guards against a template edit introducing a token the generator doesn't fill
            StringAssert.DoesNotContain("{{", html);
            StringAssert.Contains("Generated by Tiver.Fowl", html);
        }

        [Test]
        public void Generate_SummaryReflectsResultCounts()
        {
            var html = GenerateHtml(
            [
                CreateRecord("Tests.Sample.PassedOne", TestResult.Passed),
                CreateRecord("Tests.Sample.PassedTwo", TestResult.Passed),
                CreateRecord("Tests.Sample.FailedOne", TestResult.Failed),
                CreateRecord("Tests.Sample.SkippedOne", TestResult.Unknown)
            ]);

            StringAssert.Contains("stat-value text-base-content\">4<", html);
            StringAssert.Contains("stat-value text-success\">2<", html);
            StringAssert.Contains("stat-value text-error\">1<", html);
            StringAssert.Contains("stat-value text-warning\">1<", html);
        }

        [Test]
        public void Generate_GroupsTestsByNamespace()
        {
            var html = GenerateHtml(
            [
                CreateRecord("Tests.Catalog.SelectCategory", TestResult.Passed),
                CreateRecord("Tests.Checkout.PlaceOrder", TestResult.Failed)
            ]);

            StringAssert.Contains("data-ns=\"tests.catalog\"", html);
            StringAssert.Contains("data-ns=\"tests.checkout\"", html);

            // Only the method name is shown in the row; the namespace becomes the group header
            StringAssert.Contains(">SelectCategory<", html);
            StringAssert.Contains(">PlaceOrder<", html);
        }

        [Test]
        public void Generate_RendersStepsWithNestedActions()
        {
            var record = CreateRecord("Tests.Sample.TestWithActions", TestResult.Passed);
            record.AddPreStepAction(new ElementActionRecord
            {
                ElementType = "Button", ElementName = "InitialButton", Action = "Click"
            });

            var step = new TestStepRecord { StepNumber = 1, Description = "Open catalog section" };
            step.AddAction(new ElementActionRecord
            {
                ElementType = "Textbox", ElementName = "Username", Action = "Type"
            });
            record.AddStep(step);

            var html = GenerateHtml([record]);

            StringAssert.Contains("Open catalog section", html);
            StringAssert.Contains("InitialButton", html);
            StringAssert.Contains("Username", html);

            // 1 step / 2 actions counter on the test row
            StringAssert.Contains(">1s/2a<", html);
        }

        [Test]
        public void Generate_HtmlEncodesTextFromTestData()
        {
            var record = CreateRecord("Tests.Sample.EncodingTest", TestResult.Failed);
            record.ErrorMessage = "Expected <b>true</b> & got false";

            var step = new TestStepRecord { StepNumber = 1, Description = "<script>alert('xss')</script>" };
            step.AddAction(new ElementActionRecord
            {
                ElementType = "Button", ElementName = "Save & Close", Action = "Click"
            });
            record.AddStep(step);

            var html = GenerateHtml([record]);

            StringAssert.DoesNotContain("<script>alert('xss')</script>", html);
            StringAssert.Contains("&lt;script&gt;", html);
            StringAssert.Contains("Save &amp; Close", html);
            StringAssert.Contains("Expected &lt;b&gt;true&lt;/b&gt; &amp; got false", html);
        }

        [Test]
        public void Generate_CreatesMissingOutputDirectory()
        {
            var directory = CreateTempDirectory();
            try
            {
                var outputPath = Path.Combine(directory, "nested", "reports", "report.html");

                HtmlReportGenerator.Generate(
                    [CreateRecord("Tests.Sample.PassingTest", TestResult.Passed)],
                    outputPath);

                ClassicAssert.IsTrue(File.Exists(outputPath));
            }
            finally
            {
                Directory.Delete(directory, true);
            }
        }

        [Test]
        public void Generate_HandlesEmptyResults()
        {
            var html = GenerateHtml([]);

            StringAssert.Contains("stat-value text-base-content\">0<", html);
            StringAssert.DoesNotContain("{{", html);
        }

        [Test]
        public void EmbeddedTemplateIsShippedInsideTheAssembly()
        {
            // This project resolves the template from disk (ProjectReference copies it to the
            // output), so the embedded copy that package consumers depend on is never exercised
            // here. Assert it is present, otherwise dropping the EmbeddedResource item from
            // Tiver.Fowl.csproj would only break the NUnit/MSTest consumer suites.
            using var stream = typeof(HtmlReportGenerator).Assembly
                .GetManifestResourceStream("Tiver.Fowl.report-template.html");

            ClassicAssert.IsNotNull(stream, "report-template.html is not embedded in Tiver.Fowl.dll");

            using var reader = new StreamReader(stream);
            var template = reader.ReadToEnd();

            foreach (var placeholder in new[] { "{{TITLE}}", "{{SUMMARY}}", "{{TESTS}}", "{{FOOTER}}" })
            {
                StringAssert.Contains(placeholder, template);
            }
        }

        [Test]
        public void Generate_ThrowsOnInvalidArguments()
        {
            var outputPath = Path.Combine(Path.GetTempPath(), $"tiver-report-{Guid.NewGuid():N}.html");

            Assert.Throws<ArgumentNullException>(() => HtmlReportGenerator.Generate(null, outputPath));
            Assert.Throws<ArgumentException>(() => HtmlReportGenerator.Generate([], null));
            Assert.Throws<ArgumentException>(() => HtmlReportGenerator.Generate([], "  "));
        }

        private static TestResultRecord CreateRecord(string testName, TestResult result)
        {
            var start = new DateTime(2025, 12, 18, 10, 0, 0, DateTimeKind.Utc);
            return new TestResultRecord
            {
                TestName = testName,
                Result = result,
                StartTime = start,
                EndTime = start.AddSeconds(2)
            };
        }

        private static List<TestResultRecord> ParseLog(string logContent)
        {
            var logFile = Path.GetTempFileName();
            try
            {
                File.WriteAllText(logFile, logContent.Trim());
                return LogFileParser.Parse(logFile).Values.SelectMany(r => r).ToList();
            }
            finally
            {
                File.Delete(logFile);
            }
        }

        private static string GenerateHtml(IEnumerable<TestResultRecord> results)
        {
            var directory = CreateTempDirectory();
            try
            {
                var outputPath = Path.Combine(directory, "report.html");
                HtmlReportGenerator.Generate(results, outputPath);
                return File.ReadAllText(outputPath);
            }
            finally
            {
                Directory.Delete(directory, true);
            }
        }

        private static string CreateTempDirectory()
        {
            var directory = Path.Combine(Path.GetTempPath(), $"tiver-report-{Guid.NewGuid():N}");
            Directory.CreateDirectory(directory);
            return directory;
        }
    }
}
