namespace Tiver.Fowl.Core.Reporting
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Text;
    using System.Web;
    using Enums;
    using Serilog;

    /// <summary>
    /// Generates HTML test reports from a template file with dynamic content injection.
    /// Searches multiple locations for report-template.html: current directory, base directory,
    /// entry/executing assembly directories. Falls back to the copy embedded in this assembly,
    /// so consumers that reference Tiver.Fowl as a NuGet package need no template file of their own.
    /// </summary>
    public static class HtmlReportGenerator
    {
        private const string TemplateName = "report-template.html";
        private const string EmbeddedTemplateName = "Tiver.Fowl.report-template.html";

        public static void Generate(IEnumerable<TestResultRecord> results, string outputPath)
        {
            if (results == null)
                throw new ArgumentNullException(nameof(results));
            if (string.IsNullOrWhiteSpace(outputPath))
                throw new ArgumentException("Output path cannot be null or empty", nameof(outputPath));

            var resultsList = results.ToList();

            // Ensure output directory exists
            var outputDirectory = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDirectory) && !Directory.Exists(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
                Log.Debug("Created output directory: {Directory}", outputDirectory);
            }

            var html = BuildHtmlFromTemplate(resultsList);
            File.WriteAllText(outputPath, html);
        }

        private static string LoadTemplate()
        {
            var searchPaths = new[]
            {
                // 1. Same directory as output (current working directory)
                Directory.GetCurrentDirectory(),

                // 2. Application base directory (where assemblies are loaded from)
                AppDomain.CurrentDomain.BaseDirectory,

                // 3. Entry assembly location (test project output directory)
                Path.GetDirectoryName(Assembly.GetEntryAssembly()?.Location),

                // 4. Executing assembly location (Tiver.Fowl assembly directory)
                Path.GetDirectoryName(Assembly.GetExecutingAssembly()?.Location),
            };

            foreach (var basePath in searchPaths.Where(p => !string.IsNullOrEmpty(p)))
            {
                var templatePath = Path.Combine(basePath, TemplateName);
                if (File.Exists(templatePath))
                {
                    Log.Debug("Found report template at: {TemplatePath}", templatePath);
                    return File.ReadAllText(templatePath);
                }
            }

            // NuGet consumers never get the template as a file: only assemblies flow out of a
            // package's lib/ folder into the consumer's output directory. Fall back to the copy
            // embedded in this assembly, which is always available.
            var embedded = LoadEmbeddedTemplate();
            if (embedded != null)
            {
                Log.Debug("Report template not found on disk, using the copy embedded in Tiver.Fowl");
                return embedded;
            }

            var searchedPaths = string.Join(", ", searchPaths.Where(p => !string.IsNullOrEmpty(p)));
            var errorMessage = $"Report template '{TemplateName}' not found on disk (searched: {searchedPaths}) " +
                               $"and embedded resource '{EmbeddedTemplateName}' is missing from the Tiver.Fowl assembly";
            Log.Error(errorMessage);
            throw new FileNotFoundException(errorMessage, TemplateName);
        }

        private static string LoadEmbeddedTemplate()
        {
            using var stream = typeof(HtmlReportGenerator).Assembly
                .GetManifestResourceStream(EmbeddedTemplateName);
            if (stream == null)
            {
                return null;
            }

            using var reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }

        private static string BuildHtmlFromTemplate(List<TestResultRecord> results)
        {
            var template = LoadTemplate();
            var timestamp = DateTime.Now;

            var replacements = new Dictionary<string, string>
            {
                { "{{TITLE}}", $"Test Report - {timestamp:yyyy-MM-dd HH:mm}" },
                { "{{SUMMARY}}", BuildSummary(results) },
                { "{{TESTS}}", BuildTests(results) },
                { "{{FOOTER}}", $"Generated by Tiver.Fowl on {timestamp:yyyy-MM-dd HH:mm:ss}" }
            };

            var html = template;
            foreach (var replacement in replacements)
            {
                html = html.Replace(replacement.Key, replacement.Value);
            }

            return html;
        }

        private static (string namespacePath, string methodName) ParseTestName(string fullTestName)
        {
            var lastDotIndex = fullTestName.LastIndexOf('.');
            return lastDotIndex == -1
                ? (string.Empty, fullTestName)
                : (fullTestName[..lastDotIndex], fullTestName[(lastDotIndex + 1)..]);
        }

        private static string BuildSummary(List<TestResultRecord> results)
        {
            var passed = results.Count(r => r.Result == TestResult.Passed);
            var failed = results.Count(r => r.Result == TestResult.Failed);
            var unknown = results.Count(r => r.Result == TestResult.Unknown);
            var duration = FormatDuration(TimeSpan.FromSeconds(results.Sum(r => r.Duration.TotalSeconds)));

            var sb = new StringBuilder();
            sb.AppendLine($"<div class=\"stat\"><div class=\"stat-value text-base-content\">{results.Count}</div><div class=\"stat-title\">Total</div></div>");
            if (passed > 0)
                sb.AppendLine($"<div class=\"stat\"><div class=\"stat-value text-success\">{passed}</div><div class=\"stat-title\">Passed</div></div>");
            if (failed > 0)
                sb.AppendLine($"<div class=\"stat\"><div class=\"stat-value text-error\">{failed}</div><div class=\"stat-title\">Failed</div></div>");
            if (unknown > 0)
                sb.AppendLine($"<div class=\"stat\"><div class=\"stat-value text-warning\">{unknown}</div><div class=\"stat-title\">Skipped</div></div>");
            sb.AppendLine($"<div class=\"stat\"><div class=\"stat-value text-base-content\">{duration}</div><div class=\"stat-title\">Duration</div></div>");

            return sb.ToString();
        }

        private static string BuildTests(List<TestResultRecord> results)
        {
            var sb = new StringBuilder();
            var grouped = results
                .GroupBy(r => ParseTestName(r.TestName).namespacePath)
                .OrderBy(g => g.Key);

            foreach (var group in grouped)
            {
                var nsPath = string.IsNullOrEmpty(group.Key) ? "(root)" : group.Key;
                var tests = group.OrderBy(t => t.Result == TestResult.Failed ? 0 : t.Result == TestResult.Unknown ? 1 : 2)
                                 .ThenBy(t => t.TestName).ToList();

                var gPassed = tests.Count(t => t.Result == TestResult.Passed);
                var gFailed = tests.Count(t => t.Result == TestResult.Failed);
                var gUnknown = tests.Count(t => t.Result == TestResult.Unknown);

                sb.AppendLine($"<div class=\"ns-group border-b border-base-300 last:border-b-0\" data-ns=\"{HttpUtility.HtmlAttributeEncode(nsPath.ToLowerInvariant())}\">");
                sb.AppendLine("<div class=\"flex items-center gap-2 px-4 py-3 bg-base-200 hover:bg-base-300 cursor-pointer select-none\" onclick=\"toggleNs(this)\">");
                sb.AppendLine("<span class=\"ns-icon text-base-content/60\">▼</span>");
                sb.AppendLine($"<span class=\"flex-1 font-medium text-sm text-base-content/70\">{HttpUtility.HtmlEncode(nsPath)}</span>");
                sb.AppendLine("<div class=\"flex gap-2\">");
                if (gPassed > 0) sb.AppendLine($"<span class=\"badge badge-success badge-sm\">{gPassed}</span>");
                if (gFailed > 0) sb.AppendLine($"<span class=\"badge badge-error badge-sm\">{gFailed}</span>");
                if (gUnknown > 0) sb.AppendLine($"<span class=\"badge badge-warning badge-sm\">{gUnknown}</span>");
                sb.AppendLine("</div></div>");
                sb.AppendLine("<div class=\"ns-content\">");

                foreach (var test in tests)
                {
                    var (_, methodName) = ParseTestName(test.TestName);
                    var statusClass = test.Result == TestResult.Passed ? "pass" : test.Result == TestResult.Failed ? "fail" : "skip";
                    var statusColor = test.Result == TestResult.Passed ? "success" : test.Result == TestResult.Failed ? "error" : "warning";
                    var stepCount = test.Steps.Count;
                    var actionCount = test.PreStepActions.Count + test.Steps.Sum(s => s.Actions.Count);
                    var testDuration = FormatDuration(test.Duration);
                    var expandedClass = test.Result == TestResult.Failed ? " test-expanded" : "";

                    sb.AppendLine($"<div class=\"test-row{expandedClass} flex items-center gap-3 px-4 py-3 border-t border-base-300 hover:bg-base-100 cursor-pointer\" data-result=\"{statusClass}\" data-name=\"{HttpUtility.HtmlAttributeEncode(test.TestName.ToLowerInvariant())}\" onclick=\"toggleTest(this)\">");
                    sb.AppendLine($"<div class=\"w-2 h-2 rounded-full bg-{statusColor} flex-shrink-0\"></div>");
                    sb.AppendLine($"<span class=\"flex-1 font-medium text-sm\">{HttpUtility.HtmlEncode(methodName)}</span>");
                    sb.AppendLine("<div class=\"flex items-center gap-3 text-xs text-base-content/60\">");
                    if (stepCount > 0 || actionCount > 0)
                        sb.AppendLine($"<span>{stepCount}s/{actionCount}a</span>");
                    sb.AppendLine($"<span class=\"min-w-[50px] text-right\">{testDuration}</span>");
                    sb.AppendLine("</div>");
                    sb.AppendLine("<span class=\"test-expand-icon text-base-content/60 text-xs\">▼</span>");
                    sb.AppendLine("</div>");

                    // Details
                    var detailsHidden = test.Result != TestResult.Failed ? " hidden" : "";
                    sb.AppendLine($"<div class=\"test-details{detailsHidden} px-4 py-3 bg-base-100 border-t border-base-300\">");
                    if (test.Result == TestResult.Failed)
                    {
                        if (!string.IsNullOrEmpty(test.ErrorMessage))
                            sb.AppendLine($"<div class=\"alert alert-error mb-3 text-sm\"><span class=\"font-mono text-xs\">{HttpUtility.HtmlEncode(test.ErrorMessage)}</span></div>");
                        if (!string.IsNullOrEmpty(test.StackTrace))
                            sb.AppendLine($"<div class=\"mockup-code mb-3 text-xs overflow-x-auto max-h-40\"><pre><code>{HttpUtility.HtmlEncode(test.StackTrace)}</code></pre></div>");
                        if (!string.IsNullOrEmpty(test.ScreenshotBase64))
                            sb.AppendLine($"<div class=\"mb-3\"><img src=\"data:image/png;base64,{test.ScreenshotBase64}\" class=\"max-w-xs border border-base-300 rounded-lg cursor-pointer hover:opacity-90\" onclick=\"showModal(this.src)\" alt=\"Screenshot\"></div>");
                    }
                    if (test.Steps.Count > 0 || test.PreStepActions.Count > 0)
                    {
                        sb.AppendLine("<div class=\"text-xs font-semibold text-base-content/60 uppercase mb-2\">Steps & Actions</div>");
                        sb.AppendLine("<div class=\"space-y-1\">");
                        foreach (var action in test.PreStepActions)
                            sb.AppendLine($"<div class=\"text-sm text-base-content/60\"><span class=\"font-medium\">{HttpUtility.HtmlEncode(action.ElementType)}</span> {HttpUtility.HtmlEncode(action.ElementName)} - {HttpUtility.HtmlEncode(action.Action)}</div>");
                        foreach (var step in test.Steps)
                        {
                            sb.AppendLine($"<div class=\"flex items-start gap-2 py-1\"><span class=\"badge badge-info badge-sm\">{step.StepNumber}</span><span class=\"flex-1 text-sm\">{HttpUtility.HtmlEncode(step.Description)}</span></div>");
                            if (step.Actions.Count > 0)
                            {
                                sb.AppendLine("<div class=\"ml-8 space-y-1\">");
                                foreach (var action in step.Actions)
                                    sb.AppendLine($"<div class=\"text-sm text-base-content/60\"><span class=\"font-medium\">{HttpUtility.HtmlEncode(action.ElementType)}</span> {HttpUtility.HtmlEncode(action.ElementName)} - {HttpUtility.HtmlEncode(action.Action)}</div>");
                                sb.AppendLine("</div>");
                            }
                        }
                        sb.AppendLine("</div>");
                    }
                    sb.AppendLine("</div>");
                }

                sb.AppendLine("</div></div>");
            }

            return sb.ToString();
        }

        private static string FormatDuration(TimeSpan d) =>
            d.TotalHours >= 1 ? $"{(int)d.TotalHours}h{d.Minutes}m" :
            d.TotalMinutes >= 1 ? $"{d.Minutes}m{d.Seconds}s" :
            d.TotalSeconds >= 1 ? $"{d.TotalSeconds:F1}s" : $"{d.TotalMilliseconds:F0}ms";
    }
}
