using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Tiver.Fowl.Core.Context;
using Tiver.Fowl.Core.Reporting;
using Tiver.Fowl.TestingBase;
using TestResult = Tiver.Fowl.Core.Enums.TestResult;

namespace Tests.MSTest;

/// <summary>
/// Report generation as a NuGet consumer experiences it.
///
/// This project has no report-template.html of its own and never gets one from the package:
/// NuGet only flows assemblies out of a package's lib/ folder into the consumer's output
/// directory. Generation therefore relies on the template embedded in Tiver.Fowl.dll, and this
/// fixture is the only place that fallback is exercised - the main Tests project uses a
/// ProjectReference, which copies the template file into its output.
/// </summary>
[TestClass]
public class ReportGenerationTests : BaseTestForMSTest
{
    /// <summary>A valid 1x1 transparent PNG, used to verify screenshot embedding.</summary>
    private const string OnePixelPng =
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

    [TestMethod]
    public void Generate_ResolvesTemplateWithoutATemplateFileInTheConsumerProject()
    {
        // Guards the packaging defect directly: no template file is reachable from here, so a
        // regression in how the template ships surfaces as a FileNotFoundException.
        Assert.IsFalse(
            File.Exists(Path.Combine(Directory.GetCurrentDirectory(), "report-template.html")),
            "Consumer output unexpectedly contains a template file - this fixture no longer covers the embedded fallback");

        var html = GenerateHtml([CreateRecord("Tests.MSTest.Sample.PassingTest", TestResult.Passed)]);

        StringAssert.Contains(html, "Generated by Tiver.Fowl");
        Assert.IsFalse(html.Contains("{{"), "Template placeholder left unreplaced");
    }

    [TestMethod]
    public void Generate_RendersSummaryCountsAndNamespaceGroups()
    {
        var html = GenerateHtml(
        [
            CreateRecord("Tests.MSTest.Catalog.PassedOne", TestResult.Passed),
            CreateRecord("Tests.MSTest.Catalog.PassedTwo", TestResult.Passed),
            CreateRecord("Tests.MSTest.Checkout.FailedOne", TestResult.Failed),
            CreateRecord("Tests.MSTest.Checkout.SkippedOne", TestResult.Unknown)
        ]);

        StringAssert.Contains(html, "stat-value text-base-content\">4<");
        StringAssert.Contains(html, "stat-value text-success\">2<");
        StringAssert.Contains(html, "stat-value text-error\">1<");
        StringAssert.Contains(html, "stat-value text-warning\">1<");

        StringAssert.Contains(html, "data-ns=\"tests.mstest.catalog\"");
        StringAssert.Contains(html, "data-ns=\"tests.mstest.checkout\"");
    }

    [TestMethod]
    public void Generate_RendersFailureDetailsWithScreenshot()
    {
        var record = CreateRecord("Tests.MSTest.Sample.FailingTest", TestResult.Failed);
        record.ErrorMessage = "Expected the banner to be displayed";
        record.StackTrace = "   at Tests.MSTest.Sample.FailingTest()";
        record.ScreenshotBase64 = OnePixelPng;

        var step = new TestStepRecord { StepNumber = 1, Description = "Verify the banner" };
        step.AddAction(new ElementActionRecord
        {
            ElementType = "Button", ElementName = "Continue", Action = "Click"
        });
        record.AddStep(step);

        var html = GenerateHtml([record]);

        StringAssert.Contains(html, "Expected the banner to be displayed");
        StringAssert.Contains(html, "at Tests.MSTest.Sample.FailingTest()");
        StringAssert.Contains(html, $"src=\"data:image/png;base64,{OnePixelPng}\"");
        StringAssert.Contains(html, "Verify the banner");
        StringAssert.Contains(html, "Continue");
    }

    [TestMethod]
    public void LogFileParser_ReadsTheLogWrittenByThePackagedLogger()
    {
        // End-to-end over the contentFiles that ship as source: Logger.Configure() sets up the
        // Serilog sink and the SessionId/TestName enrichers in this project's own compilation.
        this.LogStep("Step recorded by the packaged logger");

        var record = ReadCurrentSessionRecord();

        CollectionAssert.Contains(
            record.Steps.Select(s => s.Description).ToList(),
            "Step recorded by the packaged logger");
    }

    [TestMethod]
    public void Generate_RendersRecordsParsedFromTheLiveSessionLog()
    {
        this.LogStep("Step rendered into the report");

        var html = GenerateHtml([ReadCurrentSessionRecord()]);

        StringAssert.Contains(html, "Step rendered into the report");
        StringAssert.Contains(html, ">Generate_RendersRecordsParsedFromTheLiveSessionLog<");
        Assert.IsFalse(html.Contains("{{"));
    }

    /// <summary>
    /// Parse log.txt and return the record the running session recorded for the current test.
    /// The log is snapshotted first because Serilog holds the file open for the whole run.
    /// </summary>
    private TestResultRecord ReadCurrentSessionRecord()
    {
        var logPath = Path.Combine(Directory.GetCurrentDirectory(), "log.txt");
        Assert.IsTrue(File.Exists(logPath), $"Packaged logger wrote no log file at {logPath}");

        var directory = CreateTempDirectory();
        try
        {
            var snapshot = Path.Combine(directory, "log.txt");
            using (var source = new FileStream(logPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            using (var target = File.Create(snapshot))
            {
                source.CopyTo(target);
            }

            var sessions = LogFileParser.Parse(snapshot);
            Assert.IsTrue(sessions.ContainsKey(TestExecutionContext.SessionId),
                "Log contains no entries for the current SessionId");

            // Matches the full name BaseTestForMSTest builds in Setup()
            var testType = GetType();
            var fullName = $"{testType.Namespace}.{testType.Name}.{TestContext.TestName}";

            var record = sessions[TestExecutionContext.SessionId]
                .SingleOrDefault(r => r.TestName == fullName);
            Assert.IsNotNull(record, "Current session produced no parseable record for this test");

            return record;
        }
        finally
        {
            Directory.Delete(directory, true);
        }
    }

    private static TestResultRecord CreateRecord(string testName, TestResult result)
    {
        var start = new DateTime(2026, 1, 15, 10, 0, 0, DateTimeKind.Utc);
        return new TestResultRecord
        {
            TestName = testName,
            Result = result,
            StartTime = start,
            EndTime = start.AddSeconds(2)
        };
    }

    private static string GenerateHtml(IEnumerable<TestResultRecord> results)
    {
        var directory = CreateTempDirectory();
        try
        {
            var outputPath = Path.Combine(directory, "report.html");
            HtmlReportGenerator.Generate(results, outputPath);
            return File.ReadAllText(outputPath);
        }
        finally
        {
            Directory.Delete(directory, true);
        }
    }

    private static string CreateTempDirectory()
    {
        var directory = Path.Combine(Path.GetTempPath(), $"tiver-report-{Guid.NewGuid():N}");
        Directory.CreateDirectory(directory);
        return directory;
    }
}
